3box/3box-pinning-node

- package-lock.json
- server.js
This code has both the code for pubsub-room and orbit-db-pubsub for compatibility issues with people who are on an older beta version of our library. We should remove this when we have released 3box-js 1.0.0.
> Use odb-pubsub in paralell to pubsub-room

- README.md
- server.js
> Cleaned up code and added pubsub responses

- package-lock.json
- package.json
- server.js
Since the server changed ipfs keys, any old version of the lib will not work anyway.
> Removed ipfs-pubsub-room dependancy

- .env.default
- .env.development
- .env.production
- .gitignore
- src/node.js
DO NOT Release until setting AWS env var to production (if not already).
> ref: use env vars, dev and prod

- package-lock.json
- package.json
- src/__tests__/pinning.test.js
- src/__tests__/util.test.js
- src/analytics.js
- src/node.js
- src/pinning.js
- src/util.js
- Add `analytics` library provided by segment
- Fire analytics events to segment based on actions (openBox, getProfile...)
- Add util module with some functions to measure things like disk space or number of directories.
cc @michaelsena we need this merged to send the events to the platform and start plotting dashboards
> Send metrics to segment

- src/__tests__/pinning.test.js
- src/pinning.js
> Solve locking issue and simplify replication logic

- src/analytics.js
- src/node.js
- Fixes an error when the write key is not defiend
- Resolves #50
> Null (& disabled) analytics

- .gitignore
- deploy.sh
- More robust pm2 management (install only if needed)
- `.env` files should not be versioned, just the example ones
- `git reset` ensures local branch is always synced up with the remote branch (I saw merge commits between local and remote branch). This can also be achieved with a combination of `fetch/rebase`
> Improvements to the CI/CD flow

- package-lock.json
- src/__tests__/cache.test.js
- src/__tests__/cacheService.test.js
- src/analytics.js
- src/cache.js
- src/cacheService.js
- src/pinning.js
This PR adds the ability to query public space data though a REST API that is similar to the "getProfile" api.
There are now two additional endpoints:
* `space` - lists the public data of a users space, is called with a user address and space name
* `list-spaces` - lists all spaces that a user have, is called with a users address
> feat(api): Add support to query public space data

- src/cacheService.js
> fix(cacheService): don't normalize space names :S

- README.md
- package.json
Finally decided to just rename this package 🙂
> chore: update title

- src/pinning.js
> fix(pinning): getConfig correctly

- src/pinning.js
Return address-links in getConfig by default. Don't think it's needed in getProfile.
> feat(api): add address-links to getConfig results

- src/pinning.js
Localized fix of https://github.com/orbitdb/orbit-db/pull/688, that could be used before orbitdb release.
> fix: local orbitdb change, wait to consumer/exchange heads until store ready

- RELEASE-NOTES.md
- package.json
- src/messageBroker.js
- src/node.js
- src/pinning.js
- src/util.js
The following steps will be taken:
> release v1.7.0

- src/pinning.js
Simply adds an extra field that we look for in an PIN_DB / SYNC_DB requests.
> feat: support extra field for muport backwards compatibility

- package-lock.json
- package.json
Fix in orbit redis cache to pass env args (ie host)
> fix: cache args fix, version up

- package-lock.json
- src/__tests__/pinning.test.js
- src/node.js
- src/pinning.js
- src/s3.js
- Allow s3 endpoint, signature version and path-style access to be set by env var
- Also allow pinning room to be set by env var (fixes https://github.com/3box/3box-services-box/issues/22)
> configure s3 client options and pinning room

- package.json
- src/pinning.js
Reference branch 3box on our fork which can maintain, and continue to rebase on commits in orbit as we upgrade until those changes are added in an orbit release.
> feat: send heads on connect, with orbit fix, remove wait

- src/node.js
- src/pinning.js
- src/util.js
* specify whitelist of DIDs for whom to process pin requests through environment variable
* add PIN_SILENT flag to prevent sending HAS_ENTRIES responses (client not able to handle multiple pinning servers responding to requests)
> only process pin requests with specified dids

- .circleci/config.yml
- Dockerfile
- package-lock.json
- package.json
- src/healthcheckService.js
- src/logger.js
- src/pinning.js
> Add bunyan logger

- .circleci/config.yml
- Dockerfile
- RELEASE-NOTES.md
- package-lock.json
- package.json
- src/__tests__/pinning.test.js
- src/healthcheckService.js
- src/logger.js
- src/node.js
- src/pinning.js
* feat: add CODE_VERSION to dockerfile, circle ci image build step, and logger
* feat: add bunyan logger
* refactor: move ipfs init into main module, use ipfs-http-client instead of ipfs if IPFS_API_URL env var is set
> Release v1.13.0

- Dockerfile
Just a reference to current temporary hotfix release, includes dockerfile and package lock used
> fix: lock and version up, hotfix release

- src/pinning.js
> IPFS node metrics

- src/healthcheckService.js
Make sure this works on develop :)
> chore: log ulimit on healthcheck

- .circleci/config.yml
- package-lock.json
- package.json
- src/healthcheckService.js
- src/pinning.js
- add leak listener and head diff
- catch possible exceptions on orbitdb `db` close
> chore(pinning): add heap inspection

- src/s3.js
- add AWS logs and more config
> AWS config

- src/pinning.js
> Catch errors

- src/s3.js
> feat(pinning): enable caching

- src/s3.js
- add TTL config for S3 datastore cache entries
> feat(pinning): add TTL opts for S3 datastore cache entries
